name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.4.4
  - seaborn=0.11.2
  - pandas=1.4.3
  - pandas-profiling=3.2.0
  - pyarrow=8.0.0
  - wandb==0.12.21
  - ipywidgets=7.6.5