name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=22.1.2
  - requests=2.28.1
  - mlflow=1.27.0
  - scikit-learn=1.1.1
  - pip:
      - wandb==0.12.21
      - git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components
